[package]
name = "fpcli"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

flatpak-rs = "0.8"

clap = { version = "3", features = ["derive"] }
